import FormDataProvider from '@/context/FormDataContext';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FormDataProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </FormDataProvider>
  );
}
