import { ClerkProvider } from '@clerk/nextjs';
import '../globals.css';
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider afterSignInUrl="/onboarding" afterSignUpUrl="/onboarding">
      <html lang="en">
        <body>
          {children}
          <ToastContainer />
        </body>
      </html>
    </ClerkProvider>
  );
}
